Script started on 2017年06月14日 (週三) 00時33分33秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab8 $[00m ./tetris[4Pmakescript lab8.scriptmake[K./tetris[K./tetris[4Pmake
g++ -c genMino.cpp
g++ -o tetris tetris.o genMino.o Mino.o MinoI.o MinoS.o MinoJ.o MinoL.o MinoO.o
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab8 $[00m make./tetris
generated 10000000 minos
generated 10000000 minos
Exception : std::bad_alloc
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab8 $[00m 
Script done on 2017年06月14日 (週三) 00時33分50秒
