Script started on 2017年06月13日 (週二) 23時17分04秒
^[[A[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab8 $[00m vi genMino.cppmake[Kvi genMino.cpp[6P./tetrisvi genMino.cpp[6P./tetris[4Pmake
g++ -c genMino.cpp
g++ -o tetris tetris.o genMino.o Mino.o MinoI.o MinoS.o MinoJ.o MinoL.o MinoO.o
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab8 $[00m makevi genMino.cppmake[Kvi genMino.cpp[6P./tetris
generated 30000000 minos
generated 30000000 minos
Killed
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab8 $[00m exit

Script done on 2017年06月13日 (週二) 23時25分56秒
